version: "3.9"

services:
  caddy-dns-updater:
    image: mbradley672/caddy-cloudflare-updater:latest
    container_name: caddy-dns-updater
    restart: unless-stopped
    environment:
      # Required Cloudflare settings
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - CF_DOMAIN=${CF_DOMAIN}
      
      # Optional settings
      - CADDYFILE_PATH=/etc/caddy/Caddyfile
      - LOG_LEVEL=INFO
      - RUN_MODE=watcher  # Options: once, watcher, cron, hybrid
      
    volumes:
      # Mount your Caddyfile (adjust the left path to your actual Caddyfile location)
      - /path/to/your/Caddyfile:/etc/caddy/Caddyfile:ro
      
      # Optional: Mount log directory to host for persistence
      - ./logs:/var/log
    
    # Only needed if you want to access logs via HTTP
    # ports:
    #   - "8080:8080"
